### ISSUE TITLE
WADL has incorrect base URL

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wmdr#10]
(moved from https://github.com/wmo-cop/wmo-oscar/issues/11)

When inspecting https://oscar.wmo.int/surface/rest/api?_wadl, in `/application/`, the URL below is invalid/does not work.

```xml
<resources base="http://127.0.0.1:9181/OSCAR/rest/api">
```

**Comment by joergklausen** [comment]
The WADL is created automatically. The base URL is indeed incorrect, but can be guessed correctly.

**Comment by tomkralidis** [comment]
Sure, but then what is the point of emitting an incorrect URL?  The idea of WADL (and other API description languages) is to provide binding information that is then used for further interaction.  A client does not assume that a given API base URL is consistent throughout, and uses the values in the WADL to continue interaction.

In addition, I'm not sure what security implications are involved (http://localhost:9181 lets everyone know the underlying port used in the application.

Happy to keep closed/workaround for now.
