### ISSUE TITLE
Treatment of supervising organization vs station contacts in OSCAR/Surface vs WMDS vs WMDR

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wmdr#18]
(moved from https://github.com/wmo-cop/wmo-oscar/issues/32)

- WMDS
Element 9-01 is supervising *organization* without specific cardinality
- WMDR
ObservingFacility\responsibleParty is of type RepsonsibleParty which is modeled using CI_ResponsibleParty and has cardinality  [1..*]. CI_RespojnsibleParty allows specification of individual Name, etc
- OSCAR/Surface
The element is interpreted as WMDS element 9-01, and only the *organization* is extracted. Cardinality [1..1] is imposed at any one time.
--> Need to agree on cardinality and range of elements (only organization, or full contact) that can be expressed.

**Comment by joergklausen** [comment]
@tomkralidis I believe this is resolved and can be closed. Can you confirm?
