### ISSUE TITLE
Include OSCAR as source for exported WMDR XML

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wmdr#22]
(moved from https://github.com/wmo-cop/wmo-oscar/issues/38)

Include OSCAR (at least URL) as source for exported WMDR XMLs.

**Comment by joergklausen** [comment]
Downloaded XML files contain following information in the header:

<gmd:CI_OnlineResource>
    <gmd:linkage>
        <gmd:URL>https://oscar.wmo.int/surface</gmd:URL>
    </gmd:linkage>
</gmd:CI_OnlineResource>
