### ISSUE TITLE
JSON Examples

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wmdr#24]
(moved from https://github.com/wmo-cop/wmo-oscar/issues/41)

Please provide JSON payload examples.

**Comment by joergklausen** [comment]
@tomkralidis Is this still relevant?

**Comment by tomkralidis** [comment]
This was moved from https://github.com/wmo-cop/wmo-oscar/issues/41 deferring to @rowan-met who opened the issue.

**Comment by rowan-met** [comment]
If memory serves me correctly you allow JSON payloads to interact with the OSCAR metadata database? In your examples you only provide XML and not JSON.

**Comment by joergklausen** [comment]
Hi @rowan-met, I am afraid your memory fails you, at present, the API only supports XML. The discussion about JSON popped up a few times, but a requirement  was never clearly specified. I will close this issue now. If you have a requirement for JSON support of the OSCAR/Surface API, please open a support ticket in OSCAR/Surface directly. Thanks
