### ISSUE TITLE
Metadata upload failure using pyoscar against DEPL

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wmdr#25]
cc @thineshsornalingam

Hi: doing an HTTP POST to https://oscardepl.wmo.int/surface/rest/api/wmd/upload with a WMDR file using [pyoscar](https://github.com/wmo-cop/pyoscar) results in a 401.  My API token is valid/has not expired.

Any ideas?

**Comment by luciacap** [comment]
Your token is no longer valid because it was overwritten. Please generate a new token on the productive system (https://oscar.wmo.int/surface) and use it for your tests on the test environment (https://oscardepl.wmo.int/surface)  starting from the following Monday.

**Comment by tomkralidis** [comment]
Works, thanks.
