### ISSUE TITLE
API stations query: filter by facilitytype

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wmdr#33]
Using the OSCAR API, how can one search stations (i.e. https://oscar.wmo.int/surface/rest/apisearch/station) and be able to filter on station type?

I see a `facilityType` in the WADL, would this work?  Is there a domain set for this value?

**Comment by joergklausen** [comment]
https://oscar.wmo.int/surface/rest/api/search/station?facilityType=xyz,
where xyz is one or a comma-separated list of element(s) from http://codes.wmo.int/wmdr/FacilityType. 
Example: https://oscar.wmo.int/surface/rest/api/search/station?facilityType=landMobile,airMobile
