### ISSUE TITLE
API stations query: get last modified

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wmdr#34]
How can one use the API to get a listing of recently changed stations?

Use case is being able to sync station metadata (workflow is OSCAR to internal NMHS) without having to do an entire round trip of fetching all stations and figuring out locally every time (thus saving bandwith and only providing relevant results).  Example is getting only stations whose metadata has been changed in the last 7 days.

**Comment by joergklausen** [comment]
This is not supported by the OSCAR/Surface API. However, an OAI-PMH interface has been implemented at https://oscar.wmo.int/oai/oaisearch.do that would support this. You could set up your own harvester to keep all records in sync.
